export { default as Breadcrumbs } from "./Breadcrumbs";
export { default as Tooltip } from "./Tooltip/Tooltip";
export { default as Table } from "./Table/Table";
// export { default as RcTable } from "./RcTable/RcTable";
export { default as MainHeader } from "./MainHeader";
export { default as FormInput } from "./Form/FormInput";
export { default as FormSelect } from "./Form/FormSelect";
export { default as DatePicket } from "./Form/DatePicket";
export { default as UploadFile } from "./Form/UploadFile";
export { default as SelectSection } from "./Form/SelectSection";
export { default as DeleteTableRowDialog } from "./DeleteTableRowDialog";
export { default as TableSection } from "./TableSection";
import { RTable } from "./RTable_";
export { RTable };
